/*************
 �౾����
SPI�������ļ�

 2018.2.10
**************/
#include "SPI_Init.h"

//SSI0: CLK:PA2  FSS:PA3  RX:PA4  TX:PA5
//SSI1: CLK:PD0  FSS:PD1  RX:PD2  TX:PD3
//SSI2: CLK:PB4  FSS:PB5  RX:PB6  TX:PB7
//SSI3: CLK:PD0  FSS:PD1  RX:PD2  TX:PD3
const spi_data_t spi_array[4]=
{
   {
    .SYSCTL_PERIPH_SSI=SYSCTL_PERIPH_SSI0,
    .SYSCTL_PERIPH_GPIO=SYSCTL_PERIPH_GPIOA,

    .GPIO_PORT_SSI_BASE=GPIO_PORTA_BASE,
    .GPIO_SSI_CLK=GPIO_PA2_SSI0CLK,
    .GPIO_SSI_FSS=GPIO_PA3_SSI0FSS,
    .GPIO_SSI_RX=GPIO_PA4_SSI0RX,
    .GPIO_SSI_TX=GPIO_PA5_SSI0TX,
    .GPIO_SSI_PINS=GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_4|GPIO_PIN_5,

    .SSI_BASE=SSI0_BASE,

    .SSI_PROTOCOL=SSI_FRF_MOTO_MODE_1,
    .SSI_BIT_RATE=50000,
    .SSI_DATA_WIDTH=16,
  },
  {
    .SYSCTL_PERIPH_SSI=SYSCTL_PERIPH_SSI1,
    .SYSCTL_PERIPH_GPIO=SYSCTL_PERIPH_GPIOD,

    .GPIO_PORT_SSI_BASE=GPIO_PORTD_BASE,
    .GPIO_SSI_CLK=GPIO_PD0_SSI1CLK,
    .GPIO_SSI_FSS=GPIO_PD1_SSI1FSS,
    .GPIO_SSI_RX=GPIO_PD2_SSI1RX,
    .GPIO_SSI_TX=GPIO_PD3_SSI1TX,
    .GPIO_SSI_PINS=GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_1|GPIO_PIN_0,

    .SSI_BASE=SSI1_BASE,

    .SSI_PROTOCOL=SSI_FRF_MOTO_MODE_1,
    .SSI_BIT_RATE=50000,
    .SSI_DATA_WIDTH=16,
  },
  {
    .SYSCTL_PERIPH_SSI=SYSCTL_PERIPH_SSI2,
    .SYSCTL_PERIPH_GPIO=SYSCTL_PERIPH_GPIOB,

    .GPIO_PORT_SSI_BASE=GPIO_PORTB_BASE,
    .GPIO_SSI_CLK=GPIO_PB4_SSI2CLK,
    .GPIO_SSI_FSS=GPIO_PB5_SSI2FSS,
    .GPIO_SSI_RX=GPIO_PB6_SSI2RX,
    .GPIO_SSI_TX=GPIO_PB7_SSI2TX,
    .GPIO_SSI_PINS=GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_4|GPIO_PIN_5,

    .SSI_BASE=SSI2_BASE,

    .SSI_PROTOCOL=SSI_FRF_MOTO_MODE_1,
    .SSI_BIT_RATE=50000,
    .SSI_DATA_WIDTH=16,
   },
   {
    .SYSCTL_PERIPH_SSI=SYSCTL_PERIPH_SSI3,
    .SYSCTL_PERIPH_GPIO=SYSCTL_PERIPH_GPIOD,

    .GPIO_PORT_SSI_BASE=GPIO_PORTD_BASE,
    .GPIO_SSI_CLK=GPIO_PD0_SSI3CLK,
    .GPIO_SSI_FSS=GPIO_PD1_SSI3FSS,
    .GPIO_SSI_RX=GPIO_PD2_SSI3RX,
    .GPIO_SSI_TX=GPIO_PD3_SSI3TX,
    .GPIO_SSI_PINS=GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_1|GPIO_PIN_0,

    .SSI_BASE=SSI3_BASE,

    .SSI_PROTOCOL=SSI_FRF_MOTO_MODE_1,
    .SSI_BIT_RATE=50000,
    .SSI_DATA_WIDTH=16,
   },
};


void ConfigureSPI(int mode,void (* SSI_Handler)(void))
{
    MAP_SysCtlPeripheralEnable(spi_array[mode].SYSCTL_PERIPH_SSI);
    MAP_SysCtlPeripheralEnable(spi_array[mode].SYSCTL_PERIPH_GPIO);

    MAP_GPIOPinConfigure(spi_array[mode].GPIO_SSI_CLK);
    MAP_GPIOPinConfigure(spi_array[mode].GPIO_SSI_FSS);
    MAP_GPIOPinConfigure(spi_array[mode].GPIO_SSI_RX);
    MAP_GPIOPinConfigure(spi_array[mode].GPIO_SSI_TX);
    MAP_GPIOPinTypeSSI(spi_array[mode].GPIO_PORT_SSI_BASE,
                   spi_array[mode].GPIO_SSI_PINS);

    MAP_SSIConfigSetExpClk(spi_array[mode].SSI_BASE,MAP_SysCtlClockGet(),
                       spi_array[mode].SSI_PROTOCOL,SSI_MODE_MASTER,
                       spi_array[mode].SSI_BIT_RATE,
                       spi_array[mode].SSI_DATA_WIDTH);
    MAP_SSIEnable(spi_array[mode].SSI_BASE);

    (* SSI_Handler)();
}
